format_version: 10
pipelines:
  pingpong_build:
    group: RHTWD_build
    label_template: '${COUNT}-${pingpong_build[:7]}'
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      pingpong_build:
        git: https://github.com/rahul-rakshit/pingpong
        shallow_clone: false
        auto_update: true
        branch: trunk
    stages:
      - docker_build:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            docker_build:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - '-c'
                      - 'docker build . -t rahulrakshit/pingpong:latest'
                      - 'docker tag rahulrakshit/pingpong:latest -t rahulrakshit/pingpong:${GO_PIPELINE_LABEL}'
                    run_if: passed
                - exec:
                    command: /bin/bash
                    arguments:
                      - '-c'
                      - 'docker tag rahulrakshit/pingpong:latest rahulrakshit/pingpong:${GO_PIPELINE_LABEL}'
                    run_if: passed
      - docker_push:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            docker_push:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - '-c'
                      - 'docker push rahulrakshit/pingpong:latest'
                    run_if: passed
                - exec:
                    command: /bin/bash
                    arguments:
                      - '-c'
                      - 'docker push rahulrakshit/pingpong:${GO_PIPELINE_LABEL}'
                    run_if: passed
